fix: address inconsistent parameter and mapping order (OZ N-05)
graphprotocol/contracts pull request #1034
Opened 2024-09-18 13:11 UTC by MoonBoi9001

### Motivation:

- This PR addresses the [following N-05 OZ audit issue](https://defender.openzeppelin.com/#/audit/9d56f9fe-e25e-4ac5-acb0-772150889078/issues/N-05), applying the recommended fixes.

### Title: 
N-05 Inconsistent Parameter and Mapping Order

### Details: 
In the HorizonStaking contract, the [_isAuthorized function](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStaking.sol#L949) has the following parameter order: _operator, _serviceProvider, _verifier. On the other hand, the [_operatorAuth mapping](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStakingStorage.sol#L162) uses this order: _serviceProvider, _verifier, _operator. In addition, the [_legacyOperatorAuth variable](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStakingStorage.sol#L108) is defined as a mapping from an operator to a service provider to a boolean status. However, [it is being used](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStaking.sol#L937) as a mapping from a service provider to an operator to a boolean status.

These inconsistencies can lead to confusion and potential errors during integration or modification, as developers may misinterpret the correct parameter order.

Consider aligning the parameter order in both the _isAuthorized function and the _operatorAuth mapping for improved consistency. Moreover, consider updating the keys and value names in the _legacyOperatorAuth mapping definition to match its usage.

##

### Key changes

- Aligned the parameter order in both the _isAuthorized function and the _operatorAuth mapping for improved consistency

2024-09-18 13:11 UTC, MoonBoi9001 commented
##

### Did not address:

- > In addition, the [_legacyOperatorAuth variable](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStakingStorage.sol#L108) is defined as a mapping from an operator to a service provider to a boolean status. However, [it is being used](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStaking.sol#L937) as a mapping from a service provider to an operator to a boolean status.
  - This point was already addressed. 

 - > Moreover, consider updating the keys and value names in the _legacyOperatorAuth mapping definition to match its usage.
   - I'm unsure what changes need to happen given:
   - `mapping(address serviceProvider => mapping(address legacyOperator => bool authorized)) internal _legacyOperatorAuth;`
   - I presume the suggestion is to change `authorized` to `allowed`? [See here](https://github.com/graphprotocol/contracts/blob/f47cf916c40b1d7aa10204d510ca1364c144736d/packages/horizon/contracts/staking/HorizonStaking.sol#L937)

2024-09-19 20:34 UTC, tmigone requested changes
We should also update `isAuthorized()` external function, and probably in the `tests/` folder there are cases where we call this function and we need to switch the param order as well. For example: https://github.com/graphprotocol/contracts/blob/95b3f83b1abe85449a63ab4922e84896f989ac57/packages/horizon/test/shared/horizon-staking/HorizonStakingShared.t.sol#L758

2024-09-20 10:21 UTC, MoonBoi9001 commented
Presumably this would also imply updating _getStorage_OperatorAuth

https://github.com/graphprotocol/contracts/blob/95b3f83b1abe85449a63ab4922e84896f989ac57/packages/horizon/test/shared/horizon-staking/HorizonStakingShared.t.sol#L757

2024-09-20 14:57 UTC, tmigone commented
Yes good idea being consistent. I wouldn't mind keeping `_getStorage_OperatorAuth` as is because its an internal test only function, but anything that's externally accessible it does seem like a good idea to be consistent.

2024-10-02 18:21 UTC, MoonBoi9001 commented
New Proposed consistent order after discussions with Pablo:
### (ServiceProvider, Operator, Verifier)

2024-10-04 17:59 UTC, tmigone commented on packages/horizon/contracts/data-service/utilities/ProvisionManager.sol
>       * @param caller The address of the caller.
```suggestion
     * @param serviceProvider The address of the serviceProvider.
```

2024-10-04 18:13 UTC, pcarranzav commented
> Hey @MoonBoi9001 @pcarranzav curious why you chose `(ServiceProvider, Operator, Verifier)` over `(ServiceProvider, Verifier, Operator)`? All the other staking functions follow the `(ServiceProvider, Verifier, ...)` pattern

I don't feel strongly about it, but to me it made intuitive sense that:
- Operator and service provider are closely related, so it made sense to have them close to each other
- It is coherent with other functions having (serviceProvider, verifier) because the ordering is transitive, i.e. (serviceProvider, operator), (operator, verifier), (serviceProvider, verifier) are valid orderings for functions that have only two of the three. And we already have some functions with (operator, verifier).

But if you think the other ordering is cleaner I'm happy with that too; but would prefer if the "transitiveness" was enforced, e.g. setOperator and setOperatorLocked should be changed to (verifier, operator, allowed) as well

2024-10-04 18:31 UTC, tmigone commented
I see. I think I still prefer to keep the (serviceProvider, verifier, ...) pattern, I feel like it's easier to remember, but I do agree we need to change SetOperator and SetOperatorLocked as well to enforce the transitiveness.

2024-10-04 18:33 UTC, pcarranzav commented
I'm happy with that, @MoonBoi9001 sorry for the churn, how do you feel about changing it to (serviceProvider, verifier, operator) and checking it's transitively consistent everywhere?

2024-10-04 18:40 UTC, MoonBoi9001 commented
Okay, will do that.

2024-10-08 23:15 UTC, pcarranzav approved these changes
Looks great 👍

2024-10-09 09:34 UTC, merged

2024-11-13 17:30 UTC, tmigone commented
thanks @MoonBoi9001 and sorry for the trouble 👍