fix: override type in CLI to allow wrapping contract calls
graphprotocol/contracts pull request #911
Opened 2024-01-11 19:21 UTC by pcarranzav

2024-01-11 19:24 UTC, Maikol submitted a review, later dismissed

2024-01-11 19:52 UTC, tmigone requested changes
Nice! 

Can you also make this change in the SDK? `packages/sdk/src/deployments/lib/contracts/tx-log.ts`

2024-01-11 19:58 UTC, tmigone commented
Btw this code duplication problem should be resolved once we get rid of the cli folder.

2024-01-12 01:48 UTC, tmigone approved these changes
Approving so you can merge but left one comment!

2024-01-12 01:48 UTC, tmigone commented on packages/sdk/src/deployments/lib/contracts/tx-log.ts
>      wrappedContract.functions[fn] = override
We should remove:
```
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
```

2024-01-12 13:30 UTC, tmigone approved these changes

2024-01-12 14:32 UTC, merged